spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**
            - id: payment-service-route
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**
            - id: cart-service-route
              uri: lb://cart-service
              predicates:
                - Path=/api/v1/carts/**
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

#kendini eurekaya tanitiyor(kaydediyor bilgilerini)
#ba?ka serviceleri de kullanarak yönlendirme alabiliyor
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"


server:
  port: 8888