services:
  config-server:
    image: nursultanaslan/turkcell-45-config-server
    ports:
      - "8989:8989"
  discovery-server:
    image: nursultanaslan/tcell-45-discovery-server
    ports:
      - "8761:8761"
  gateway-server:
    image: nursultanaslan/tcell-45-gateway-server
    ports:
      - "8888:8888"
    depends_on:
      - config-server
    environment:
      - CONFIG_URI=http://config-server:8989
  order-service:
    image: nursultanaslan/tcell-order-service
    ports:
      - "8082:8082"
    environment:
      - CONFIG_URI=http://config-server:8989
  cart-service:
    image: nursultanaslan/tcell-45-cart-service
    ports:
      - "8083:8083"
    environment:
      - CONFIG_URI=http://config-server:8989
  product-service:
    image: nursultanaslan/tcell-45-product-service
    ports:
      - "8080:8080"
    environment:
      - CONFIG_URI=http://config-server:8989
  payment-service:
    image: nursultanaslan/tcell-45-payment-service
    ports:
      - "8081:8081"
    environment:
      - CONFIG_URI=http://config-server:8989