#Sıfır bir makinede (FreeDos) bu projeyi nasıl kurarım?
#işletim sistemi -> java -> maven -> proje -> run


#SINGLE STAGE (ONERILMEZ) dosya boyutu büyük : Maven ve tamJDK'yı içerir.
#Gerekli olanın ötesinde araç barındırır.
#işletim sistemi -> java -> maven ✅
FROM maven:3.9-eclipse-temurin-21

#proje -> run
WORKDIR /app

COPY . .

RUN mvn dependency:purge-local-repository
RUN mvn -U clean package -DskipTests

ENTRYPOINT ["java", "-jar", "target/config-server-0.0.1-SNAPSHOT.jar"]