spring:
  application:
    name: discovery-server

server:
  port: 8761

#false yapt?k çünkü discovery-service'in kendini eurekaya kaydetmeye
#veya ba?ka service'leri aramaya ihtiyac? yok
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/