#konfigurasyonlari nereden çekecegimi belirleyecegim
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nursultanaslan/microservices-gy4.5.git
          default-label: main
          search-paths:
            - configurations
            - configurations/{application}
          clone-on-start: true
          force-pull: true
          password: <token> #reponuz private ise

server:
  port: 8989